name: CI
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  root-test:
    name: Unit Test
    runs-on: ubuntu-20.04
    timeout-minutes: 40

    strategy:
      fail-fast: false
      matrix:
        number:
          [
            1, 2, 3, 4, 5, 6, 7, 8, 9, 0,
          ]

    steps:
    - uses: actions/setup-go@v3
      with:
        go-version: 1.19.2
    - uses: actions/checkout@v3
    - name: unit test
      run: |
        go mod tidy
        sudo GOTRACEBACK=crash $(command -v go) test -race ./
