name: CI
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  root-test:
    name: Unit Test
    runs-on: ubuntu-20.04
    timeout-minutes: 40

    strategy:
      fail-fast: false
      matrix:
        number:
          [
            1, 2, 3, 4, 5, 6, 7, 8, 9, 0,
          ]

    steps:
    - uses: actions/setup-go@v3
      with:
        go-version: 1.19.2
    - uses: actions/checkout@v3
    - name: Unit test
      run: |
        cat /proc/sys/kernel/core_pattern
        ulimit -a
        go mod tidy
        sudo GOTRACEBACK=all $(command -v go) test -race ./
    - name: Check Coredump
      run: |
        ls -al /usr/share/apport/apport
      if: always()
    - name: Upload Coredump
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: coredump
        path: |
          /usr/share/apport/apport/*
